### PR TITLE
Minor fix transaction consumption confirmation

### LINKED ISSUE #1053: Allow to confirm a transaction consumption regardless of transaction request expiration
Currently, it fails and returns the expiration reason.

Refer to the following scenario:
```
Noting this discussion down for reference. Consider this scenario:

1. Provider creates a transaction request
2. User consumes the transaction request with amount override -> pending consumption created
3. Provider cancelled the transaction request created in Step 1
4. Provider approves the consumption from Step 2 -> a successful transaction occurs

This is allowed since there can be cases where a provider wishes to stop accepting new payments but allow users that are mid-way through the process to continue to the end.
```

_Originally posted by @unnawut in https://github.com/omisego/ewallet/pull/1046#issuecomment-500714144_

### PR DESCRIPTION
**Pull request by ripzery**
Issue/Task Number: #1053 

Closes #1053 

# Overview

This PR allows the transaction consumption with an expired transaction request with `expiration_reason = "expired_transaction_request"` to be confirmed

> ⚠️  Waiting branch 950-add-endpoint-cancel-transaction-request to be merged

### CODE REVIEW

File: apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex [hunk 1]
```diff
@@ -149,6 +149,9 @@ defmodule EWallet.TransactionConsumptionValidator do
       :cancelled_transaction_request ->
         :ok
 
+      "expired_transaction_request" ->
```
Comment (unnawut) [inline apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex]: How about applying `String.to_existing_atom/1` since `|> Kernel.||(request.expiration_reason)`? 
This way we have more consistent typing + work is done closer to the source.

Comment (T-Dnzt) [reply apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex]: I like the idea.

Comment (ripzery) [reply apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex]: The `request.expiration_reason` can be nil, so need to validate it before converting to :atom.

In my thought, it will be become this.

```elixir
expiration_reason =
      request.expiration_reason &&
        String.to_existing_atom(request.expiration_reason)

    request
    |> TransactionRequest.valid?()
    |> Kernel.||(expiration_reason)
    |> Kernel.||(TransactionRequest.get_cancelled_error(request))
    |> do_validate_transaction_request(operation)
```
Not sure if I have a better choice 🤔

Comment (unnawut) [reply apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex]: Looks fine to me, although I'd like it explicit than a boolean shortcut e.g.

```elixir
expiration_reason =
  case request.expiration_reason do
    nil -> nil
    reason -> String.to_existing_atom(reason)
  end
```

Could turn this into its own function in `TransactionRequest` as well, can imagine it being re-used in other places.

Comment (ripzery) [reply apps/ewallet/lib/ewallet/validators/transaction_consumption_validator.ex]: oh right would be better to move to `TransactionRequest` 🙇

File: apps/ewallet/test/ewallet/gates/transaction_consumption_confirmer_gate_test.exs [hunk 2]
```diff
@@ -708,7 +709,8 @@ defmodule EWallet.TransactionConsumptionConfirmerGateTest do
           %System{}
         )
 
-      assert res == {:error, :expired_transaction_request}
+      assert status == :ok
```
Comment (unnawut) [inline apps/ewallet/test/ewallet/gates/transaction_consumption_confirmer_gate_test.exs]: But the test name is `"fails to confirm the consumption if expired"`?

File: apps/ewallet/test/ewallet/validators/transaction_consumption_validator_test.exs [hunk 3]
```diff
@@ -179,11 +179,40 @@ defmodule EWallet.TransactionConsumptionValidatorTest do
           end_user: user
         })
 
-      assert status == :error
-      assert res == :expired_transaction_request
+      assert status == :ok
```
Comment (unnawut) [inline apps/ewallet/test/ewallet/validators/transaction_consumption_validator_test.exs]: But the test name is `"expires request if past expiration date"`?

File: apps/ewallet/test/ewallet/gates/transaction_consumption_confirmer_gate_test.exs [hunk 4]
```diff
@@ -379,7 +379,8 @@ defmodule EWallet.TransactionConsumptionConfirmerGateTest do
...
```
Comment (unnawut) [inline apps/ewallet/test/ewallet/gates/transaction_consumption_confirmer_gate_test.exs]: But the test name is for `"fails to confirm the consumption if expired"`?
