### PR TITLE
Fix /user.get_transactions wrong parameters

### LINKED ISSUE #1022: /user.get_transactions endpoint accept user_id instead of id
**Describe the bug**
When calling /user.get_transactions endpoint, it accepts user_id instead of id.
So when you pass id it will give you invalid params error.

**To Reproduce**
```
curl 'http://localhost:4000/api/admin/user.get_transactions' -H 'Accept: application/vnd.omisego.v1+json' -H 'Referer: http://localhost:9000/admin/users/usr_01d7kdqzwhvtmm6cdsgnhrm92d/transactions' -H 'Origin: http://localhost:9000' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36' -H 'Authorization: OMGAdmin dXNyXzAxZDdicmJzbmhmemNuMHlucmNlenJ3Z3dxOkg5V0EyU1FOSVBDS0J2OUs5QTA3dVYzdW9NUk1lSEJ3d3lvcFJFYzJhQzQ=' -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"id":"usr_01d7kdqzwhvtmm6cdsgnhrm92d","page":1,"per_page":10,"sort_by":"created_at","sort_dir":"desc"}' --compressed
```

**Expected behavior**
Should accept id param

**Additional context**
-

### PR DESCRIPTION
**Pull request by T-Dnzt**
Issue/Task Number: #1022 
closes #1022 

# Overview

This PR adds the proper parameter for the endpoint: `id` (instead of `user_id` and `provider_user_id` - those are still supported but `user_id` shouldn't be used anymore and isn't documented.

# Changes

- Add a test
- Fix endpoint

### CODE REVIEW

File: mix.exs [hunk 1]
```diff
@@ -37,7 +37,8 @@ defmodule EWallet.Umbrella.Mixfile do
       {:distillery, "~> 1.5", runtime: false},
       {:ex_doc, "~> 0.19", only: [:dev, :test], runtime: false},
       {:excoveralls, "~> 0.8", only: :test, runtime: false},
-      {:junit_formatter, "~> 3.0", only: :test}
+      {:junit_formatter, "~> 3.0", only: :test},
+      {:httpoison, "~> 0.11.0"}
```
Comment (unnawut) [inline mix.exs]: Hmm where is this used?

Comment (T-Dnzt) [reply mix.exs]: I had trouble doing a `mix deps.get`, it was updating httpoison to a later version and clash with other dependencies :/ I had to fix it at the top level to be able to start the app...

Comment (T-Dnzt) [reply mix.exs]: Seems to be fine now... removing it 🤦‍♂
