### PR TITLE
Fix a race condition while testing for simultaneous transfers on an insufficient fund

### LINKED ISSUE #652: Random test failure: test #insert raises an InsufficientFundsError with two inserts happening at the same time and not enough funds
The move from Jenkins to CircleCI might have changed the machine profile significantly enough that tests are running faster and slower to some degree, and hence impacts what tests are executed in parallel and so we're seeing more random test failures.

https://circleci.com/gh/omisego/ewallet/1587:

```ex
  1) test #insert raises an InsufficientFundsError with two inserts happening at the
          same time and not enough funds (LocalLedger.TransactionTest)
     test/local_ledger/transaction_test.exs:393
     ** (EXIT from #PID<0.5365.0>) an exception was raised:
         ** (MatchError) no match of right hand side value: {:ok, %LocalLedgerDB.Transaction{__meta__: #Ecto.Schema.Metadata<:loaded, "transaction">, encrypted_metadata: %{}, entries: [%LocalLedgerDB.Entry{__meta__: #Ecto.Schema.Metadata<:loaded, "entry">, amount: 100, inserted_at: ~N[2019-01-14 07:02:08.815057], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_id: "tok_OMG_01cbepz0mhzb042vwgaqv17cjy", transaction: #Ecto.Association.NotLoaded<association :transaction is not loaded>, transaction_uuid: "263e92d9-338e-4944-b31a-86cca58f5bd5", type: "debit", updated_at: ~N[2019-01-14 07:02:08.815062], uuid: "9d62b2ea-7a3f-4816-9559-2d8e89ee3475", wallet: #Ecto.Association.NotLoaded<association :wallet is not loaded>, wallet_address: "mederic"}, %LocalLedgerDB.Entry{__meta__: #Ecto.Schema.Metadata<:loaded, "entry">, amount: 100, inserted_at: ~N[2019-01-14 07:02:08.815423], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_id: "tok_OMG_01cbepz0mhzb042vwgaqv17cjy", transaction: #Ecto.Association.NotLoaded<association :transaction is not loaded>, transaction_uuid: "263e92d9-338e-4944-b31a-86cca58f5bd5", type: "credit", updated_at: ~N[2019-01-14 07:02:08.815428], uuid: "03a034e2-14f5-48d1-995c-fe3e92a38d8a", wallet: #Ecto.Association.NotLoaded<association :wallet is not loaded>, wallet_address: "sirn"}], idempotency_token: "fe3f1a3b-58ce-45ef-82d8-4359d8b3d10b", inserted_at: ~N[2019-01-14 07:02:08.814720], metadata: %{}, updated_at: ~N[2019-01-14 07:02:08.814726], uuid: "263e92d9-338e-4944-b31a-86cca58f5bd5"}}
             test/local_ledger/transaction_test.exs:408: anonymous fn/1 in LocalLedger.TransactionTest."test #insert raises an InsufficientFundsError with two inserts happening at the\n          same time and not enough funds"/1
             (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
             (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

07:02:08.865 [error] Postgrex.Protocol (#PID<0.1881.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5365.0> exited with: an exception was raised:
    ** (MatchError) no match of right hand side value: {:ok, %LocalLedgerDB.Transaction{__meta__: #Ecto.Schema.Metadata<:loaded, "transaction">, encrypted_metadata: %{}, entries: [%LocalLedgerDB.Entry{__meta__: #Ecto.Schema.Metadata<:loaded, "entry">, amount: 100, inserted_at: ~N[2019-01-14 07:02:08.815057], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_id: "tok_OMG_01cbepz0mhzb042vwgaqv17cjy", transaction: #Ecto.Association.NotLoaded<association :transaction is not loaded>, transaction_uuid: "263e92d9-338e-4944-b31a-86cca58f5bd5", type: "debit", updated_at: ~N[2019-01-14 07:02:08.815062], uuid: "9d62b2ea-7a3f-4816-9559-2d8e89ee3475", wallet: #Ecto.Association.NotLoaded<association :wallet is not loaded>, wallet_address: "mederic"}, %LocalLedgerDB.Entry{__meta__: #Ecto.Schema.Metadata<:loaded, "entry">, amount: 100, inserted_at: ~N[2019-01-14 07:02:08.815423], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_id: "tok_OMG_01cbepz0mhzb042vwgaqv17cjy", transaction: #Ecto.Association.NotLoaded<association :transaction is not loaded>, transaction_uuid: "263e92d9-338e-4944-b31a-86cca58f5bd5", type: "credit", updated_at: ~N[2019-01-14 07:02:08.815428], uuid: "03a034e2-14f5-48d1-995c-fe3e92a38d8a", wallet: #Ecto.Association.NotLoaded<association :wallet is not loaded>, wallet_address: "sirn"}], idempotency_token: "fe3f1a3b-58ce-45ef-82d8-4359d8b3d10b", inserted_at: ~N[2019-01-14 07:02:08.814720], metadata: %{}, updated_at: ~N[2019-01-14 07:02:08.814726], uuid: "263e92d9-338e-4944-b31a-86cca58f5bd5"}}
        test/local_ledger/transaction_test.exs:408: anonymous fn/1 in LocalLedger.TransactionTest."test #insert raises an InsufficientFundsError with two inserts happening at the\n          same time and not enough funds"/1
        (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
.07:02:08.880 [error] Task #PID<0.5367.0> started from #PID<0.5365.0> terminating
** (MatchError) no match of right hand side value: {:ok, %LocalLedgerDB.Transaction{__meta__: #Ecto.Schema.Metadata<:loaded, "transaction">, encrypted_metadata: %{}, entries: [%LocalLedgerDB.Entry{__meta__: #Ecto.Schema.Metadata<:loaded, "entry">, amount: 100, inserted_at: ~N[2019-01-14 07:02:08.815057], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_id: "tok_OMG_01cbepz0mhzb042vwgaqv17cjy", transaction: #Ecto.Association.NotLoaded<association :transaction is not loaded>, transaction_uuid: "263e92d9-338e-4944-b31a-86cca58f5bd5", type: "debit", updated_at: ~N[2019-01-14 07:02:08.815062], uuid: "9d62b2ea-7a3f-4816-9559-2d8e89ee3475", wallet: #Ecto.Association.NotLoaded<association :wallet is not loaded>, wallet_address: "mederic"}, %LocalLedgerDB.Entry{__meta__: #Ecto.Schema.Metadata<:loaded, "entry">, amount: 100, inserted_at: ~N[2019-01-14 07:02:08.815423], token: #Ecto.Association.NotLoaded<association :token is not loaded>, token_id: "tok_OMG_01cbepz0mhzb042vwgaqv17cjy", transaction: #Ecto.Association.NotLoaded<association :transaction is not loaded>, transaction_uuid: "263e92d9-338e-4944-b31a-86cca58f5bd5", type: "credit", updated_at: ~N[2019-01-14 07:02:08.815428], uuid: "03a034e2-14f5-48d1-995c-fe3e92a38d8a", wallet: #Ecto.Association.NotLoaded<association :wallet is not loaded>, wallet_address: "sirn"}], idempotency_token: "fe3f1a3b-58ce-45ef-82d8-4359d8b3d10b", inserted_at: ~N[2019-01-14 07:02:08.814720], metadata: %{}, updated_at: ~N[2019-01-14 07:02:08.814726], uuid: "263e92d9-338e-4944-b31a-86cca58f5bd5"}}
    test/local_ledger/transaction_test.exs:408: anonymous fn/1 in LocalLedger.TransactionTest."test #insert raises an InsufficientFundsError with two inserts happening at the\n          same time and not enough funds"/1
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<1.96908490/0 in LocalLedger.TransactionTest."test #insert raises an InsufficientFundsError with two inserts happening at the\n          same time and not enough funds"/1>
    Args: []
```

### PR DESCRIPTION
**Pull request by unnawut**
Issue/Task Number: #652
Closes #652

# Overview

This PR attempts to fix a random test failure which seems to result from the race condition between two transactions in the same test.

# Changes

- Updated a `LocalLedger.Transaction.insert/2` test to generate many more transactions within a short timeframe instead of two.
- Used `Task.async/1` with `Task.yield_many/2` instead of `Task.start_link/1` and many `ExUnit.Assertions.assert_receive/3`

# Implementation Details

- Generated 200 transactions within 0 - 100ms to better simulate simultaneous transactions
- With `Task.async/1` and `Task.yield_many/2` we can handle a lot of spawned tasks in one go, which would be very difficult with `Task.start_link/1` and `assert_receive/3`

# Usage

Run `mix test` should return with all passing tests.

# Impact

No changes to the DB schema or API specs.

### CODE REVIEW

File: apps/local_ledger/test/local_ledger/transaction_test.exs [hunk 1]
```diff
@@ -390,22 +390,33 @@ defmodule LocalLedger.TransactionTest do
...
-      pid = self()
+      caller_pid = self()
+      num_spawns = 200
+      amount_per_transaction = 2
+      timeout_ms = 10_000
 
-      assert get_current_balance("mederic") == 150
-      assert get_current_balance("thibault") == 150
-      assert get_current_balance("sirn") == -200
+      balance_mederic = get_current_balance("mederic")
```
Comment (mederic-p) [inline apps/local_ledger/test/local_ledger/transaction_test.exs]: Can we change names to Alice Bob and Chuck? :p
